packages:
  - .
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - shadcn@4.14.1
overrides:
  find-my-way: 9.7.0
  postcss: 8.5.22
  sharp: 0.35.3
  valibot: 1.4.2
